services:
  - type: web
    runtime: node
    name: mohammad-umar-portfolio
    branch: master
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
